name: Run tests and upload coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests and upload coverage
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)

      # Step 4: Run tests and generate coverage report
      - name: Run tests and generate coverage
        run: |
          install.packages("covr")
          covr::codecov()

      # Step 5: Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Set this token in your repository secrets
