---
title: "wildRtrax-SOP.Rmd"
author: "Alex MacPhail"
date: "01/05/2023"
output: html_document
---

# wildRtrax SOP {-}

# Introduction

# Summary of Procedures

## Initial development setup

### Creating a development branch

Before you begin making any changes to the package, it's important to create a development branch in your version control system. This branch will allow you to work on the package without affecting the main branch that others may be using. Here's an example of how to create a development branch using Git:

css
Copy code
git checkout development
This command creates a new branch called "dev" and checks it out so that you can start making changes to the package.

objectivec
Copy code
R CMD check my_package.tar.gz
This command will run a series of tests to ensure that the package is functioning as expected. It will report any issues it finds, such as errors or warnings, which you'll need to address before moving on to the next step.

## Package management

### Collaboration

To ensure that your changes are well-received by other developers and colleagues, it's important to collaborate with them and ask for feedback. This can be done using code reviews, pull requests, or other collaboration tools.

### General maintenance

### Running tests

In addition to the tests that are run by R CMD check, it's a good idea to write your own tests to ensure that the package functions as expected. You can do this using the testthat package. Here's an example of how to write a test:

Copy code
library(testthat)

test_that("my_function returns the correct output", {
  result <- my_function(5)
  expect_equal(result, 10)
})
This code tests a hypothetical function called my_function to ensure that it returns the correct output when given an input of 5. You can run all of your tests using the devtools::test() command.

### Building the package

It's important to make sure that all of your package dependencies are up to date and that there are no conflicts between packages. You can do this using the devtools::check() command. Here's an example:

scss
Copy code
library(devtools)
check()
This code will check your package dependencies and report any issues it finds.

### Stylistic considerations

To ensure that your code is stylistically consistent and correct, it's a good idea to use a linter such as lintr. Here's an example of how to run lintr on your package:

scss
Copy code
library(lintr)
lint_package()
This code will check your package for issues such as unused variables, unneeded parentheses, and other stylistic concerns.


### Issue management





## Creating a local project


### Building functions


#### Creating vignettes


#### Updating the long-form: wildRtrax "the book"


#### Pushing to development


#### Testing and merging to main

Section 7: Pushing to the main branch
Once you're satisfied that your package is working correctly, it's time to merge your changes into the main branch. You can do this using the git merge command. Here's an example:

css
Copy code
git checkout main
git merge dev
This code switches to the main branch and merges in the changes from the development branch.

By following these steps, you can ensure that your R package is thoroughly tested and verified before it is pushed to the main branch.


# Work Breakdown Structure

# Responsible Personnel



