# Introduction

## Environmental sensors

Environmental sensors are devices used to measure and record various environmental parameters, such as temperature, humidity, pressure, light, and sound. These sensors can be used to monitor changes in the environment over time and provide valuable information about the conditions that wildlife species experience in their habitats.

In wildlife ecology, environmental sensors are commonly used to study the behavior, habitat preferences, and distribution of wildlife species. For example, temperature sensors can be used to monitor the microclimate of an animal's habitat and determine the effects of temperature on its behavior and physiology. Humidity sensors can be used to study the impact of moisture on the distribution and abundance of species in different ecosystems. Sound sensors, principally, autonomous recording units (or ARUs) can be used to detect and identify the vocalizations of animals, allowing researchers to study communication patterns, behavior, population size, density, habitat preference, movement and many other biological metrics. 

Environmental sensors can also be used to monitor changes in the environment caused by human activities, such as deforestation, pollution, and climate change. By measuring and recording changes in environmental conditions, researchers can better understand the impact of these activities on wildlife species and develop effective conservation strategies to protect them.

## Open data

Open data refers to data that is freely available for anyone to access, use, and share. Open data is important in the context of environmental sensors because it allows researchers, scientists, and policymakers to access and use data collected by sensors to gain insights into environmental conditions and make informed decisions.

Environmental sensors generate large amounts of data on various environmental parameters such as audio recordings and images. By making this data openly available, researchers can analyze it to gain insights into patterns and trends over time, leading to a better understanding of environmental conditions and the impact of human activities on the environment. Open data also promotes transparency and accountability in environmental research. It allows the public to access and understand the data used to inform decisions about environmental management and conservation. Additionally, open data can lead to the development of innovative solutions and technologies that can help address environmental challenges. 

Open data also helps promote reproducibility ensuring independent verification of the data. Reproducibility ensures that the methods used to collect and analyze the data are transparent and can be independently verified by other researchers, ensuring that the results are reliable and accurate, establishing scientific validity. 

## Standardizing information pipelines

Standardized workflows can help with environmental sensor data by ensuring that data is collected, processed, and analyzed in a consistent and transparent manner. This helps to ensure that the data is reliable and accurate, and can be easily compared and combined with other data sets. Standardized workflows typically involve a series of steps that are designed to ensure that data is collected and analyzed consistently across different research projects and sites. These steps may include:

* **Pre-processing**: Cleaning and filtering the raw sensor data to remove any noise or errors.
* **Quality control**: Checking the data for outliers or errors, and making corrections or adjustments as necessary.
* **Processing**: Transforming and extracting species from the raw sensor data
* **Verification**: Ensuring the species detections are correct
* **Analysis**: This step involves applying statistical or other analytical methods to the data to extract meaningful insights or calculate biological metrics.
* **Reporting**: Presenting the results of the analysis in a clear and understandable format, such as charts, graphs or tabular data. 

By standardizing these workflows, researchers can ensure that data is collected and analyzed consistently across different projects and organizations, reducing the risk of errors or inconsistencies. This helps to ensure that the data is reliable and accurate, and can be used to inform decisions related to environmental management and conservation. In addition, standardized workflows can facilitate data sharing and collaboration among researchers, as it ensures that data is collected and processed in a manner that is consistent with best practices and widely accepted standards. This can help to promote data integration and interoperability, enabling researchers to combine data from different sources to gain a more comprehensive understanding of environmental conditions and the impact of human activities on the environment.

## What is **WildTrax**?

[**WildTrax**](https://www.wildtrax.ca) is a web-enabled portal designed to manage, store, process, share and discover environmental sensor data and the  **biological data** extracted from the media. WildTrax was developed by the [Alberta Biodiversity Monitoring Institute](https://abmi.ca). `wildRtrax` serves as a parallel design and indicator to WildTrax for future analytics and functionalities.

## Why did you build `wildRtrax`?

By outlining a standardized and harmonized procedure for data intake, quality control, processing and verification of acoustic data from autonomous recording units (ARUs), `wildRtrax` and WildTrax hope to provide open work flows for using ARUs to answer meaningful biological questions in order to inform conservation and decision-making.

## Installing the package

You can install `wildRtrax` directly from this repository with:

```r
# install.packages("remotes")
remotes::install_github("ABbiodiversity/wildRtrax")
```

Or the development version with:

```r
remotes::install_github("ABbiodiversity/wildRtrax@development")
```

## Usage

All functions begin with a `wt_*` prefix. Column names and metadata align with the WildTrax infrastructure. The goal is to follow the work flow of pre-processing, linking with WildTrax, download and analysis. 

